name: Test all projects

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_erc:
    name: Run KiCad ERC(s)
    runs-on: ubuntu-24.04
    container:
      image: maartin0/kicadutils

    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v4

      - name: Run DRC(s)
        run: find . -name "*.kicad_pcb" -print0 | xargs -0 -n1 sh -c './bin/test/drc.sh "$0" || exit 255'

  test_drc:
    name: Run KiCad DRC(s)
    runs-on: ubuntu-24.04
    container:
      image: maartin0/kicadutils

    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v4

      - name: Run DRC(s)
        run: find . -name "*.kicad_pcb" -print0 | xargs -0 -n1 sh -c './bin/test/drc.sh "$0" || exit 255'

  test_relative:
    name: Check for non-relative paths
    runs-on: ubuntu-24.04

    steps:
      - name: Check for non-relative paths
        run: find . -name "*-lib-table" -print0 | xargs -0 -n1 sh -c './bin/test/relative.sh "$0" || exit 255'
