name: Run KiCad DRC on changed PCB(s)

on:
  push:
    paths:
      - "**/*.kicad_pcb"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/*.kicad_pcb"
          matrix: true

  run:
    name: Run KiCad DRC
    runs-on: ubuntu-latest

    needs: changed-files

    strategy:
      matrix:
        pcb: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v4

      - name: Run DRC
        uses: maartin0/kicad-drc-action@v1
        with:
          pcb: ${{ matrix.pcb }}
