name: Run KiCad ERC on changed schematic(s)

on:
  push:
    paths:
      - "**/*.kicad_sch"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/*.kicad_sch"
          matrix: true

  run:
    name: Run KiCad ERC
    runs-on: ubuntu-latest

    needs: changed-files

    strategy:
      matrix:
        sch: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v4

      - name: Run ERC
        uses: maartin0/kicad-erc-action@v1
        with:
          sch: ${{ matrix.sch }}
